// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/Combined.tsx": () => import("../components/mockups/landing/Combined.tsx"),
  "./components/mockups/landing/Dramatisk.tsx": () => import("../components/mockups/landing/Dramatisk.tsx"),
  "./components/mockups/landing/Filmisk.tsx": () => import("../components/mockups/landing/Filmisk.tsx"),
  "./components/mockups/landing/Premium.tsx": () => import("../components/mockups/landing/Premium.tsx")
};
